### ISSUE TITLE
(NoMethodError) Trouble executing bin/yg-export.rb

### ISSUE THREAD

**Issue by mreacher** [jonbartlett/yahoo-groups-export#1]
Hello, I'm having some trouble executing `ruby bin/yg-export.rb`:
```
D, [2019-09-26T18:12:13.915031 #40738] DEBUG -- : MONGODB | Topology type 'unknown' initializing.
D, [2019-09-26T18:12:13.915217 #40738] DEBUG -- : MONGODB | Server 127.0.0.1:27017 initializing.
D, [2019-09-26T18:12:14.589441 #40738] DEBUG -- : MONGODB | Topology type 'unknown' changed to type 'single'.
D, [2019-09-26T18:12:14.589553 #40738] DEBUG -- : MONGODB | Server description for 127.0.0.1:27017 changed from 'unknown' to 'standalone'.
D, [2019-09-26T18:12:14.589619 #40738] DEBUG -- : MONGODB | There was a change in the members of the 'single' topology.
Traceback (most recent call last):
	3: from bin/yg-export.rb:14:in `<main>'
	2: from bin/yg-export.rb:14:in `new'
	1: from /Volumes/storage/Users/username/Work/discourse/yahoo/yahoo-groups-export/lib/yahoo-group/connection.rb:14:in `initialize'
/Volumes/storage/Users/username/Work/discourse/yahoo/yahoo-groups-export/lib/yahoo-group/connection.rb:28:in `login': undefined method `[]=' for nil:NilClass (NoMethodError)
```

When I step into this a bit further, I'm finding that it's crashing in `mechanize.rb`:
```
 => 464:   page = @agent.fetch uri, method, headers, parameters, referer
# where:
#   uri == https://login.yahoo.com
#   method == get
#   headers == {}
#   parameters == []
#   referer = "#<Mechanize::Page {url nil} {meta_refresh#<Mechanize::Page:0x2fc3458db94a>"
```

Could it be that I need to change the Yahoo URI?

**Comment by tfmm** [comment]
@mreacher did you ever find a resolution to this? I'm thinking it may be related to Captchas, as if I'm understanding the code correctly, it's not finding a field named password on the second page of the login process.

**Comment by mreacher** [comment]
Unfortunately no... with the urgent situation of the Yahoo Groups shutdown now I had to go with a commercial solution that seems to have done the trick.

**Comment by jonbartlett** [comment]
@tfmm @mreacher just pushed an update which should fix this. Let me know otherwise.

**Comment by tfmm** [comment]
@jonbartlett It is indeed working now. Thanks
